### ISSUE TITLE
Privacy Policy link overlap

### ISSUE THREAD

**Issue by slifty** [GenderAvenger/gatally#13]
The privacy policy link overlaps with the time who's talking button on iOS.

Layout needs to be adjusted so that the overlap doesn't happen any longer.

![image uploaded from ios](https://user-images.githubusercontent.com/208884/40868281-60226c56-65d9-11e8-8302-76dc5082db54.jpg)

**Comment by slifty** [comment]
Looking into this, I think the issue is that there is too much on the intro page for mobile in general.

I've tried removing some of the text on mobile screens, and I think it looks reasonable:

![image](https://user-images.githubusercontent.com/208884/40869989-8738aa84-65f3-11e8-8375-29f8611b0d94.png)

Feedback appreciated!

**Comment by GAFounder** [comment]
I agree.  Too much copy. How about just saying, "Welcome to GenderAvenger tallying because women's voices count"  - still too much?
